### ISSUE TITLE
Copy-paste typo in README

### ISSUE THREAD

**Issue by ValentinMezev** [criptalia/spanish-dni-validator#1]
Hello, you have a small typo in the README. I tried fixing but I have no permissions

![nifs](https://user-images.githubusercontent.com/10400983/235669790-e7be12b3-5f7c-49d0-a2ec-584a544b5a18.jpg)

**Comment by ale-rinaldi** [comment]
Wooops! Thank you @ValentinMezev , I fixed it 👍
